name: Auto Update Launcher Links
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependence
        run: pip install requests
      - name: Run Spider Script
        run: python scrape.py
      - name: Commit & Push
        run: |
          git config user.name "link-bot"
          git config user.email "bot@example.com"
          git add list.json
          git commit -m "Auto refresh version links" || echo "No changes skip commit"
          git push

